const EmployeList = [
    { "ID": 1, "Name": "John Smith" , "IsSelected":false},
    { "ID": 2, "Name": "Sarah Johnson" , "IsSelected":false},
    { "ID": 3, "Name": "Michael Brown" , "IsSelected":false},
    { "ID": 4, "Name": "Jessica Lee" , "IsSelected":false},
    { "ID": 5, "Name": "David Wilson" , "IsSelected":false},
    { "ID": 6, "Name": "Emily Davis" , "IsSelected":false},
    { "ID": 7, "Name": "Andrew Clark" , "IsSelected":false},
    { "ID": 8, "Name": "Olivia Wright" , "IsSelected":false},
    { "ID": 9, "Name": "Ethan Turner" , "IsSelected":false},
    { "ID": 10, "Name": "Emma Hall" , "IsSelected":false},
    { "ID": 11, "Name": "William White" , "IsSelected":false},
    { "ID": 12, "Name": "Sophia Anderson" , "IsSelected":false},
    { "ID": 13, "Name": "James Martinez" , "IsSelected":false},
    { "ID": 14, "Name": "Ava Thompson" , "IsSelected":false},
    { "ID": 15, "Name": "Benjamin Harris" , "IsSelected":false},
    { "ID": 16, "Name": "Mia Walker" , "IsSelected":false},
    { "ID": 17, "Name": "Alexander Lewis" , "IsSelected":false},
    { "ID": 18, "Name": "Harper Baker", "IsSelected":false },
    { "ID": 19, "Name": "Daniel Green" , "IsSelected":false},
    { "ID": 20, "Name": "Amelia Taylor" , "IsSelected":false},
    { "ID": 21, "Name": "Samuel Young" , "IsSelected":false},
    { "ID": 22, "Name": "Charlotte Hill" , "IsSelected":false},
    { "ID": 23, "Name": "Joseph Cooper" , "IsSelected":false},
    { "ID": 24, "Name": "Grace Garcia" , "IsSelected":false},
    { "ID": 25, "Name": "Jackson Allen", "IsSelected":false },
    { "ID": 26, "Name": "Madison Cook" , "IsSelected":false},
    { "ID": 27, "Name": "Henry Ross" , "IsSelected":false},
    { "ID": 28, "Name": "Lily Nelson" , "IsSelected":false},
    { "ID": 29, "Name": "Isaac Murphy" , "IsSelected":false},
    { "ID": 30, "Name": "Harper Collins" , "IsSelected":false}
  ];
  
export default EmployeList;
